name: node_js CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    continue-on-error: ${{ matrix.node == 20 }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm ci

    - name: Package lock check
      run: make validate-no-uncommitted-package-lock-changes

    - name: Extract i18n
      run: npm run i18n_extract

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run test

    - name: Build
      run: npm run build

    - name: Run Coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
